import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import UseAccount from "../sections/UseAccount";
import { useAccount, Web3Button } from "@web3modal/react";
import HumanCheck from "../sections/HumanCheck";
import { CheckCircleIcon, WarningIcon } from "@chakra-ui/icons";
import {
  Box,
  Flex,
  Avatar,
  Badge,
  Text,
  Button,
  Spacer,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import axios from "axios";

export default function AddPeople() {
  const [lensId, setLensId] = useState(null);
  const [allFollowers, setAllFollowers] = useState([]);
  const { account } = useAccount();

  const address = "0xcB7eA0eC36670AA13088C4372fe8636D4D2b574f";

  useEffect(() => {
    const getLensId = async () => {
      const id = await axios
        .get(`api/getLensAccount/${address}`)
        .then((response) => {
          return response.data.result;
        });
      setLensId(id);
      return id;
    };
    getLensId();
  }, [address]);

  const shortenAddress = (address) => {
    return `${address.slice(0, 6)}...${address.slice(
      address.length - 4,
      address.length
    )}`;
  };

  useEffect(() => {
    const getLensFollowers = async (id) => {
      axios.get(`api/getLensFollowers/${id}`).then((response) => {
        setAllFollowers([...response.data.result.followers.items]);
        console.log("response =>", response.data.result.followers.items);
      });
    };

    if (lensId) {
      getLensFollowers(lensId);
    }
  }, [lensId]);

  const handleClick = () => {};

  return (
    <div className={styles.container}>
      <Head>
        <title>NationDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text marginTop={5} fontSize="2xl">
          Choose people to endorse
        </Text>
        <Box
          minHeight={600}
          w="100%"
          borderRadius={33}
          padding={10}
          backgroundColor="#FFF"
          marginTop={5}
          //boxShadow="0 0 17"
        >
          {allFollowers &&
            allFollowers.map((followers) => (
              <Flex marginBottom={5} key={followers.wallet.address}>
                <Avatar
                  src={
                    followers.wallet?.defaultProfile?.picture?.original?.url &&
                    "https://ipfs.io/ipfs/" +
                      followers.wallet.defaultProfile.picture.original.url.slice(
                        7
                      )
                  }
                />
                <Box ml="3">
                  <Text fontWeight="bold">
                    {followers.wallet.defaultProfile.handle}
                    <Badge ml="1" colorScheme="green">
                      New
                    </Badge>
                  </Text>
                  <Text fontSize="sm">
                    {shortenAddress(followers.wallet.address)}
                  </Text>
                </Box>
                <Spacer />
                <Button>Click</Button>
              </Flex>
            ))}
        </Box>
      </main>
    </div>
  );
}
