import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount, Web3Button } from "@web3modal/react";
import {
  Box,
  Flex,
  Avatar,
  Badge,
  Text,
  Button,
  Spacer,
  AvatarGroup,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import axios from "axios";
import { useRouter } from "next/router";

export default function AddPeople() {
  const [lensId, setLensId] = useState(null);
  const [allFollowers, setAllFollowers] = useState([]);
  const router = useRouter();
  const { account } = useAccount();

  const address = "0xcB7eA0eC36670AA13088C4372fe8636D4D2b574f";

  const linkings = [
    "Lens follower",
    "Mirror collector",
    "Also @Buidler DAO member",
    "Also @Moonbird holder",
  ];

  useEffect(() => {
    const getLensId = async () => {
      const id = await axios
        .get(`api/getLensAccount/${address}`)
        .then((response) => {
          return response.data.result;
        });
      setLensId(id);
      return id;
    };
    getLensId();
  }, [address]);

  const shortenAddress = (address) => {
    return `${address.slice(0, 6)}...${address.slice(
      address.length - 4,
      address.length
    )}`;
  };

  const getRandom = () => {
    const random = Math.floor(Math.random() * linkings.length);
    return random;
  };

  useEffect(() => {
    const getLensFollowers = async (id) => {
      axios.get(`api/getLensFollowers/${id}`).then((response) => {
        setAllFollowers([...response.data.result.followers.items]);
        console.log("response =>", response.data.result.followers.items);
      });
    };

    if (lensId) {
      getLensFollowers(lensId);
    }
  }, [lensId]);

  const handleClick = (id) => {
    router.push(`/endorse/${id}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NationDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text marginTop={5} fontSize="2xl">
          Choose people to endorse
        </Text>
        <Box
          minHeight={600}
          w="100%"
          borderRadius={33}
          padding={10}
          backgroundColor="#FFF"
          marginTop={5}
          //boxShadow="0 0 17"
        >
          {allFollowers &&
            allFollowers.map((followers) => (
              <Flex marginBottom={5} key={followers.wallet.address}>
                <Avatar
                  src={
                    followers.wallet?.defaultProfile?.picture?.original?.url &&
                    "https://ipfs.io/ipfs/" +
                      followers.wallet.defaultProfile.picture.original.url.slice(
                        7
                      )
                  }
                />
                <Box ml="3">
                  <Text fontWeight="bold">
                    {followers.wallet.defaultProfile.handle}
                    <Badge ml="1" colorScheme="gray">
                      {shortenAddress(followers.wallet.address)}
                    </Badge>
                  </Text>
                  <Text fontSize="sm">{linkings[getRandom()]}</Text>
                </Box>
                <Spacer />

                {/* <AvatarGroup size="sm" max={3} marginRight={20}>
                  <Avatar
                    name="Ryan Florence"
                    src="https://bit.ly/ryan-florence"
                  />
                  <Avatar
                    name="Segun Adebayo"
                    src="https://bit.ly/sage-adebayo"
                  />
                  <Avatar name="Kent Dodds" src="https://bit.ly/kent-c-dodds" />
                  <Avatar
                    name="Prosper Otemuyiwa"
                    src="https://bit.ly/prosper-baba"
                  />
                  <Avatar
                    name="Christian Nwamba"
                    src="https://bit.ly/code-beast"
                  />
                </AvatarGroup> */}

                <Button
                  backgroundColor={"#588BFF"}
                  color={"#FFF"}
                  onClick={() =>
                    handleClick(followers.wallet.defaultProfile.id)
                  }
                >
                  Pick
                </Button>
              </Flex>
            ))}
        </Box>
      </main>
    </div>
  );
}
