import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import UseAccount from "../sections/UseAccount";
import { useAccount, Web3Button } from "@web3modal/react";
import HumanCheck from "../sections/HumanCheck";
import { CheckCircleIcon, WarningIcon } from "@chakra-ui/icons";
import {
  Divider,
  Center,
  VStack,
  StackDivider,
  Box,
  Button,
} from "@chakra-ui/react";
import { useRouter } from "next/navigation";

const InactiveStartEndorsement = () => {
  return (
    <Button backgroundColor={"#C7C7C7"} disabled>
      Start Endorsement
    </Button>
  );
};

const StartEndorsement = () => {
  const router = useRouter();
  return (
    <Button
      backgroundColor={"#588BFF"}
      color={"white"}
      onClick={() => router.push("/addPeople")}
    >
      Start Endorsement
    </Button>
  );
};

export default function Home() {
  const { account } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>NationDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <VStack spacing={5} align="flex" alignItems={"center"}>
            <Box h="100px" fontSize="2xl" as="b">
              Dorse your way in web3
            </Box>
            <Box h="100px">
              <Web3Button />
            </Box>

            <Box h="100px">
              <HumanCheck />{" "}
              {account.isConnected ? (
                <CheckCircleIcon w={3} h={3} color="green.500" />
              ) : (
                <WarningIcon w={3} h={3} color="red.500" />
              )}
              {
                //account.isConnected && (
                // <>
                //</>  <UseAccount />
                //</></>
                //)
              }
            </Box>
            {account.isConnected ? (
              <StartEndorsement />
            ) : (
              <InactiveStartEndorsement />
            )}
          </VStack>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by NationDO
        </a>
      </footer>
    </div>
  );
}
