import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Box,
  Flex,
  Avatar,
  Badge,
  Text,
  Button,
  Spacer,
} from "@chakra-ui/react";

export default function Success() {
  return (
    <div>
      <Head>
        <title>NationDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text marginTop={20} fontSize="2xl" as="b">
          Congrats! You endorse an SBT for them!
        </Text>
        <Box textAlign={"center"}>
          <Box
            height={350}
            width={350}
            bgGradient="linear(to-r, #FFF490, #FFD0B6)"
            //backgroundColor={"red"}
            marginTop={20}
            borderRadius={30}
            padding={10}
            textAlign={"left"}
          >
            <Text as="b">@joestars.lens is good at:</Text>
            <Text marginTop={3} fontSize="2xl">
              [Javascript], [Solidity], [NextJs]
            </Text>
            <Text marginTop={30}>Endorsed by:</Text>
            <Text as="b">@sinaxyz</Text>
          </Box>
        </Box>
      </main>
    </div>
  );
}
